---

# Initialize the Language
language: python

# Declare Docker Service to be used in the build
services: docker

# Environments variables for test
env:

    # Global
    global:
        - ROLE_NAME: nexus
        - AUTHOR: jetune
    matrix:
        - MOLECULE_DISTRO: centos6
        - MOLECULE_DISTRO: centos7
        - MOLECULE_DISTRO: ubuntu16
        - MOLECULE_DISTRO: ubuntu18

# Before install actions
before_install:
    - docker pull kubecloudsas/docker-ansible-test:centos6
    - docker pull kubecloudsas/docker-ansible-test:centos7
    - docker pull kubecloudsas/docker-ansible-test:ubuntu16
    - docker pull kubecloudsas/docker-ansible-test:ubuntu18

# Installation actions
install:

    # Install Test tools
    - pip install molecule yamllint ansible-lint docker flake8

# Test scripts
script:

    # Run Tests
    - molecule test --all

# Norifications
notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
