---

# Download Nexus archive
- name: "({{ ansible_distribution }}) NX::INSTALL - Download Nexus archive"
  get_url:
    url: "{{ nexus_download_details.url }}"
    dest: "{{ nexus_download_details.dest }}"
    checksum: "{{ nexus_download_details.checksum }}"
    timeout: 300
  register: get_url_result
  until: get_url_result is succeeded
  tags: nexus

# Unarchive Downloaded Nexus archives
- name: "({{ ansible_distribution }}) NX::INSTALL - Unarchive Downloaded Nexus archives"
  unarchive:
    src: "{{ nexus_download_details.dest }}"
    dest: "{{ _nexus_extracted_dir }}"
    creates: "{{ _nexus_extracted_dir }}/nexus-{{ nexus_version }}/bin/nexus"
    remote_src: true
  tags:
    - molecule-idempotence-notest

# Populate install directory
- name: "({{ ansible_distribution }}) NX::INSTALL - Populate install directory"
  shell:
  args:
    cmd: "mv {{ _nexus_extracted_dir }}/nexus-{{ nexus_version }}/* \
    {{ _nexus_extracted_dir }}/nexus-{{ nexus_version }}/.install4j {{ nexus_installdir }} && \
    chown -R {{ nexus_owner }}:{{ nexus_group }} {{ nexus_installdir }}"
    creates: "{{ nexus_installdir }}/bin/nexus"
    warn: true
  tags:
    - nexus
    - molecule-idempotence-notest

# Install Nexus Trustore if needed
- name: "({{ ansible_distribution }}) NX::INSTALL - Install Nexus Trustore if needed"
  copy:
    src: "{{ nexus_jvm_truststore_src_file }}"
    dest: "{{ _nexus_jvm_truststore_file }}"
    mode: u+rw-x,g+r-wx,g+r-wx
    force: true
  when:
    - nexus_jvm_truststore_install
