---

# Execute the script
- name: "({{ ansible_distribution }}) NX::API::FN::EXEC-SCRIPT - Execute the script ({{ script_name }})"
  uri:
    url: "{{ _nexus_internal_scheme }}://{{ _nexus_internal_host }}:{{ _nexus_internal_port }}\
      {{ _nexus_internal_context }}{{ _nexus_api_script_uri }}/{{ script_name }}/run"
    user: "{{ _nexus_default_user }}"
    password: "{{ current_admin_password }}"
    method: POST
    headers:
      Content-Type: "text/plain"
    force_basic_auth: true
    validate_certs: "{{ nexus_api_validate_certs }}"
    body: "{{ arguments | to_json }}"
    tags:
      - nexus
      - molecule-idempotence-notest
