---
- name: Prepare Nexus Repository Manager Server Role test
  hosts: all
  become: true
  tasks:

   # Install which command
   - name: "({{ ansible_distribution }}) - NEXUS::PREPARE - Install which command"
     package:
      name: "{{ item }}"
      state: present
     loop:
      - which
     when:
      - ansible_os_family == "RedHat"

   # Install Open JDK 8
   - name: "({{ ansible_distribution }}) - NEXUS::PREPARE - Install OpenJDK 11"
     include_role:
      name: jetune.java
     vars:
      from_repo: false
      implementation: OPENJDK
      v_major: 8
      v_minor: 40
      build: 25
      os: linux
      arch: x64
      date: 10_feb_2015
      checksum: md5:4980716637f353cfb27467d57f2faf9b
      alternative_priority: 200
      is_default: true
